// LabHelpr — Export utilities
// PDF via jsPDF, Excel via SheetJS (xlsx), Word via docx, PNG via html-to-image

// ── CSV / TSV ─────────────────────────────────────────────────────────────────
export function downloadCSV(rows: (string | number)[][], filename: string) {
  const csv = rows.map(r => r.map(c => `"${String(c).replace(/"/g, '""')}"`).join(",")).join("\n");
  triggerDownload(csv, `${filename}.csv`, "text/csv");
}

export function downloadTSV(rows: (string | number)[][], filename: string) {
  const tsv = rows.map(r => r.map(c => String(c)).join("\t")).join("\n");
  triggerDownload(tsv, `${filename}.tsv`, "text/tab-separated-values");
}

// ── Excel (xlsx) ──────────────────────────────────────────────────────────────
export async function downloadXLSX(sheets: { name: string; rows: (string | number)[][] }[], filename: string) {
  const XLSX = await import("xlsx");
  const wb = XLSX.utils.book_new();
  for (const sheet of sheets) {
    const ws = XLSX.utils.aoa_to_sheet(sheet.rows);
    XLSX.utils.book_append_sheet(wb, ws, sheet.name.slice(0, 31));
  }
  XLSX.writeFile(wb, `${filename}.xlsx`);
}

// ── LaTeX table ───────────────────────────────────────────────────────────────
export function downloadLatex(headers: string[], rows: (string | number)[][], caption: string, filename: string) {
  const cols = headers.map(() => "l").join(" | ");
  const hRow = headers.map(h => `\\textbf{${h}}`).join(" & ");
  const dataRows = rows.map(r => r.map(String).join(" & ") + " \\\\").join("\n");
  const latex = `\\begin{table}[h]
\\centering
\\caption{${caption}}
\\begin{tabular}{${cols}}
\\hline
${hRow} \\\\
\\hline
${dataRows}
\\hline
\\end{tabular}
\\end{table}`;
  triggerDownload(latex, `${filename}.tex`, "text/plain");
}

// ── PDF (jsPDF + autoTable) ───────────────────────────────────────────────────
export async function downloadPDF(
  title: string,
  sections: { heading: string; body: string }[],
  tables?: { title: string; head: string[]; rows: (string | number)[][] }[],
  filename?: string,
) {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const jsPDFLib = (await import("jspdf")) as any;
  const jsPDF = jsPDFLib.jsPDF ?? jsPDFLib.default?.jsPDF ?? jsPDFLib.default;
  const autoTable = ((await import("jspdf-autotable")) as unknown as { default: (doc: unknown, options: unknown) => void }).default;

  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const W = 210, M = 18;
  let y = 20;

  // Title
  doc.setFontSize(18);
  doc.setTextColor(30, 30, 30);
  doc.text(title, M, y);
  y += 8;

  doc.setFontSize(9);
  doc.setTextColor(120, 120, 120);
  doc.text(`Generated by LabHelpr · ${new Date().toLocaleDateString("en-GB", { day: "numeric", month: "long", year: "numeric" })}`, M, y);
  y += 8;

  // Divider
  doc.setDrawColor(200, 200, 200);
  doc.line(M, y, W - M, y);
  y += 8;

  // Sections
  for (const sec of sections) {
    if (y > 260) { doc.addPage(); y = 20; }
    doc.setFontSize(11);
    doc.setTextColor(40, 40, 40);
    doc.setFont(undefined as unknown as string, "bold");
    doc.text(sec.heading, M, y);
    y += 6;
    doc.setFont(undefined as unknown as string, "normal");
    doc.setFontSize(9);
    doc.setTextColor(80, 80, 80);
    const lines = doc.splitTextToSize(sec.body || "—", W - M * 2);
    doc.text(lines, M, y);
    y += lines.length * 5 + 6;
  }

  // Tables
  if (tables) {
    for (const tbl of tables) {
      if (y > 240) { doc.addPage(); y = 20; }
      doc.setFontSize(10);
      doc.setTextColor(40, 40, 40);
      doc.setFont(undefined as unknown as string, "bold");
      doc.text(tbl.title, M, y);
      y += 4;
      autoTable(doc, {
        startY: y,
        head: [tbl.head],
        body: tbl.rows.map(r => r.map(String)),
        margin: { left: M, right: M },
        styles: { fontSize: 8, cellPadding: 2 },
        headStyles: { fillColor: [20, 20, 35], textColor: 255 },
        alternateRowStyles: { fillColor: [245, 245, 250] },
      });
      y = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 8;
    }
  }

  doc.save(`${filename ?? title.replace(/[^a-z0-9]/gi, "_")}.pdf`);
}

// ── Word (docx) ───────────────────────────────────────────────────────────────
export async function downloadDocx(
  title: string,
  sections: { heading: string; body: string }[],
  filename?: string,
) {
  const { Document, Packer, Paragraph, TextRun, HeadingLevel } = await import("docx");

  const children: InstanceType<typeof Paragraph>[] = [];

  children.push(new Paragraph({ text: title, heading: HeadingLevel.HEADING_1 }));
  children.push(new Paragraph({ children: [new TextRun({ text: `Generated by LabHelpr · ${new Date().toLocaleDateString()}`, color: "888888", size: 18 })] }));
  children.push(new Paragraph({ text: "" }));

  for (const sec of sections) {
    children.push(new Paragraph({ text: sec.heading, heading: HeadingLevel.HEADING_2 }));
    const lines = (sec.body || "—").split("\n");
    for (const line of lines) {
      children.push(new Paragraph({ children: [new TextRun({ text: line, size: 20 })] }));
    }
    children.push(new Paragraph({ text: "" }));
  }

  const doc = new Document({ sections: [{ children }] });
  const blob = await Packer.toBlob(doc);
  const a = document.createElement("a");
  a.href = URL.createObjectURL(blob);
  a.download = `${filename ?? title.replace(/[^a-z0-9]/gi, "_")}.docx`;
  a.click();
  URL.revokeObjectURL(a.href);
}

// ── Helper ────────────────────────────────────────────────────────────────────
function triggerDownload(content: string, filename: string, mime: string) {
  const blob = new Blob([content], { type: mime });
  const a = document.createElement("a");
  a.href = URL.createObjectURL(blob);
  a.download = filename;
  a.click();
  URL.revokeObjectURL(a.href);
}
